#!/usr/bin/env bash
# script-codex-relay.sh — leaf-owned human gates relayed through the root thread.
#
# Generated by codex/script-build-codex-skills.py from codex/relay-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Contract (DEV-CX-011, approved-translation): on Claude, an eng build leaf that
# touches a database, a data file or production configuration asks the user itself
# and continues only with the answer. A Codex child thread does not own the root
# chat's input surface, so the question travels — but only the presentation moves.
# The leaf still owns the gate: it stops before acting, the root relays the leaf's
# question **verbatim**, and the answer returns to that same leaf, which resumes at
# the same checkpoint.
#
# Everything this helper refuses is a way the relay could quietly change the gate:
#
#   altered    the relayed wording, option set or default differs from the leaf's
#   misrouted  the answer was delivered to a thread that does not own the gate
#   stale      the answer was written for a different checkpoint
#   duplicate  the same gate was answered twice; the second delivery is not replayed
#
# The envelope is the output of `script-codex-gate.sh` (GATE_* lines), whose owner
# is the leaf thread. `relay` adds a digest over exactly the parts that must not
# change: the question, the ordered option set and the default.
#
# Usage:
#   script-codex-relay.sh relay   --envelope <file>
#   script-codex-relay.sh verify  --envelope <file> --relayed <file>
#   script-codex-relay.sh deliver --envelope <file> --relayed <file> \
#                                 --answer <label> --to <thread> \
#                                 [--for-resume <skill:id>] [--journal <file>]
#
# Exit codes:
#   0  RELAY_STATE=relayed | verified | delivered
#   2  usage error
#   4  RELAY_STATE=altered | misrouted | rejected — the gate was changed in transit
#   6  RELAY_STATE=stale | duplicate — the answer does not belong to this checkpoint

set -euo pipefail

usage_error() { echo "script-codex-relay.sh: $1" >&2; exit 2; }

field() { sed -n "s/^$2=//p" "$1" | head -n 1; }
fields() { sed -n "s/^$2=//p" "$1"; }

# The digest covers only what must survive the relay unchanged.
relay_digest() {
  local envelope="$1"
  {
    printf 'Q=%s\n' "$(field "$envelope" GATE_QUESTION)"
    fields "$envelope" GATE_OPTION | while IFS= read -r option; do printf 'O=%s\n' "$option"; done
    printf 'D=%s\n' "$(field "$envelope" GATE_DEFAULT)"
  } | shasum -a 256 | cut -d' ' -f1
}

require_leaf_envelope() {
  local envelope="$1" owner
  [ -f "$envelope" ] || usage_error "envelope not found: $envelope"
  owner="$(field "$envelope" GATE_OWNER)"
  [ -n "$owner" ] || usage_error "envelope has no GATE_OWNER; a leaf gate must name its leaf"
  if [ "$owner" = "root" ]; then
    usage_error "envelope is owned by root; there is nothing to relay"
  fi
  printf '%s\n' "$owner"
}

relay() {
  local envelope=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --envelope) envelope="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$envelope" ] || usage_error "--envelope is required"
  local owner; owner="$(require_leaf_envelope "$envelope")"

  # Verbatim: the leaf's own lines, reprinted unchanged, then the relay metadata.
  printf 'GATE_QUESTION=%s\n' "$(field "$envelope" GATE_QUESTION)"
  fields "$envelope" GATE_OPTION | while IFS= read -r option; do printf 'GATE_OPTION=%s\n' "$option"; done
  printf 'GATE_DEFAULT=%s\n' "$(field "$envelope" GATE_DEFAULT)"
  printf 'RELAY_FROM=%s\n' "$owner"
  printf 'RELAY_BY=root\n'
  printf 'RELAY_RESUME=%s\n' "$(field "$envelope" GATE_RESUME)"
  printf 'RELAY_DIGEST=%s\n' "$(relay_digest "$envelope")"
  echo "RELAY_STATE=relayed"
  exit 0
}

verify() {
  local envelope="" relayed=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --envelope) envelope="${2:-}"; shift 2 ;;
      --relayed) relayed="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$envelope" ] || usage_error "--envelope is required"
  [ -n "$relayed" ] || usage_error "--relayed is required"
  [ -f "$relayed" ] || usage_error "relayed file not found: $relayed"
  require_leaf_envelope "$envelope" >/dev/null

  local want got
  want="$(relay_digest "$envelope")"
  got="$(relay_digest "$relayed")"
  if [ "$want" != "$got" ]; then
    echo "RELAY_STATE=altered"
    echo "REASON=the relayed question, option set or default differs from the leaf's gate"
    printf 'EXPECTED_DIGEST=%s\n' "$want"
    printf 'RELAYED_DIGEST=%s\n' "$got"
    exit 4
  fi
  printf 'RELAY_DIGEST=%s\n' "$want"
  echo "RELAY_STATE=verified"
  exit 0
}

deliver() {
  local envelope="" relayed="" answer="" to="" resume="" journal=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --envelope) envelope="${2:-}"; shift 2 ;;
      --relayed) relayed="${2:-}"; shift 2 ;;
      --answer) answer="${2:-}"; shift 2 ;;
      --to) to="${2:-}"; shift 2 ;;
      --for-resume) resume="${2:-}"; shift 2 ;;
      --journal) journal="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$envelope" ] || usage_error "--envelope is required"
  [ -n "$relayed" ] || usage_error "--relayed is required"
  [ -n "$answer" ] || usage_error "--answer is required"
  [ -n "$to" ] || usage_error "--to is required"
  local owner; owner="$(require_leaf_envelope "$envelope")"
  [ -f "$relayed" ] || usage_error "relayed file not found: $relayed"

  local id resume_point
  id="$(field "$envelope" GATE_ID)"
  resume_point="$(field "$envelope" GATE_RESUME)"

  if [ "$(relay_digest "$envelope")" != "$(relay_digest "$relayed")" ]; then
    echo "RELAY_STATE=altered"
    echo "REASON=the answer belongs to a gate whose wording, options or default were changed in transit"
    exit 4
  fi

  # The gate is owned by the leaf that raised it; an answer routed anywhere else
  # is not an answer to this gate.
  if [ "$to" != "$owner" ]; then
    echo "RELAY_STATE=misrouted"
    printf 'REASON=gate %s is owned by %s, not %s\n' "$id" "$owner" "$to"
    exit 4
  fi

  # An answer written for another checkpoint cannot resume this one.
  if [ -n "$resume" ] && [ "$resume" != "$resume_point" ]; then
    echo "RELAY_STATE=stale"
    printf 'REASON=the answer targets %s but this gate resumes at %s\n' "$resume" "$resume_point"
    exit 6
  fi

  local option found=0
  while IFS= read -r option; do
    [ "$option" = "$answer" ] && found=1
  done < <(fields "$envelope" GATE_OPTION)
  if [ "$found" -ne 1 ]; then
    echo "RELAY_STATE=rejected"
    printf 'REASON=%s is not one of the leaf-declared options\n' "$answer"
    exit 4
  fi

  # Duplicate delivery is a no-op, not a second resume: the leaf already moved on.
  if [ -n "$journal" ] && [ -f "$journal" ] \
     && awk -F'\t' -v g="$id" '$1 == g { found = 1 } END { exit !found }' "$journal"; then
    echo "RELAY_STATE=duplicate"
    printf 'REASON=gate %s was already answered; the leaf is not resumed twice\n' "$id"
    exit 6
  fi
  [ -n "$journal" ] && printf '%s\t%s\t%s\t%s\n' "$id" "$owner" "$resume_point" "$answer" >> "$journal"

  printf 'GATE_ID=%s\n' "$id"
  printf 'GATE_ANSWER=%s\n' "$answer"
  printf 'RESUME_THREAD=%s\n' "$owner"
  printf 'RESUME_POINT=%s\n' "$resume_point"
  echo "RELAY_STATE=delivered"
  exit 0
}

main() {
  local mode="${1:-}"
  [ $# -gt 0 ] && shift || true
  case "$mode" in
    relay) relay "$@" ;;
    verify) verify "$@" ;;
    deliver) deliver "$@" ;;
    -h|--help) sed -n '2,40p' "$0" ;;
    *) usage_error "usage: $0 relay|verify|deliver [...]" ;;
  esac
}

main "$@"
