#!/usr/bin/env bash
# script-codex-resolve.sh — Codex asset path resolution for the msg harness.
#
# Generated by codex/script-build-codex-skills.py from codex/resolver-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Contract (DEV-CX-002, approved-translation): a Codex run resolves msg assets
# from Codex roots only. Claude locations are read-only migration inputs and are
# consulted solely when the user explicitly opts in with
# MSG_CODEX_ALLOW_CLAUDE_LEGACY=1. Nothing here ever writes to a Claude path.
#
# Usage:
#   script-codex-resolve.sh script <name>     # deterministic helper, e.g. script-ledger.py
#   script-codex-resolve.sh skill  <name>     # skill directory, e.g. pre-merge
#   script-codex-resolve.sh ref    <relpath>  # shared ref, e.g. refs/safety-floor.md
#   script-codex-resolve.sh roots             # print the search order, one per line
#
# Exit codes: 0 resolved (absolute path on stdout); 3 not found (designed, not an
# incident); 2 bad usage.

set -euo pipefail

repo_root() {
  local dir="${MSG_REPO_ROOT:-$PWD}"
  while [ "$dir" != "/" ]; do
    if [ -d "$dir/.agents" ] || [ -d "$dir/.git" ]; then
      printf '%s\n' "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  printf '%s\n' "$PWD"
}

agents_home() {
  printf '%s\n' "${MSG_AGENTS_HOME:-$HOME/.agents}"
}

legacy_enabled() {
  [ "${MSG_CODEX_ALLOW_CLAUDE_LEGACY:-0}" = "1" ]
}

script_roots() {
  local root
  root="$(repo_root)"
  printf '%s\n' "$root/.agents/scripts"
  printf '%s\n' "$(agents_home)/scripts"
  if legacy_enabled; then
    printf '%s\n' "$root/.claude/scripts"
    printf '%s\n' "$HOME/.claude/scripts"
  fi
}

skill_roots() {
  local root
  root="$(repo_root)"
  printf '%s\n' "$root/.agents/skills"
  printf '%s\n' "$(agents_home)/skills"
  if legacy_enabled; then
    printf '%s\n' "$root/.claude/skills"
    printf '%s\n' "$HOME/.claude/skills"
  fi
}

first_existing() {
  local target
  for target in "$@"; do
    if [ -e "$target" ]; then
      printf '%s\n' "$target"
      return 0
    fi
  done
  return 3
}

main() {
  local mode="${1:-}"
  case "$mode" in
    roots)
      script_roots
      ;;
    script)
      [ $# -eq 2 ] || { echo "usage: $0 script <name>" >&2; exit 2; }
      local candidates=()
      while IFS= read -r dir; do candidates+=("$dir/$2"); done < <(script_roots)
      first_existing "${candidates[@]}"
      ;;
    skill)
      [ $# -eq 2 ] || { echo "usage: $0 skill <name>" >&2; exit 2; }
      local candidates=()
      while IFS= read -r dir; do candidates+=("$dir/$2"); done < <(skill_roots)
      first_existing "${candidates[@]}"
      ;;
    ref)
      [ $# -eq 2 ] || { echo "usage: $0 ref <relpath>" >&2; exit 2; }
      local candidates=()
      while IFS= read -r dir; do candidates+=("$dir/shared/$2"); done < <(skill_roots)
      first_existing "${candidates[@]}"
      ;;
    *)
      echo "usage: $0 <script|skill|ref|roots> [name]" >&2
      exit 2
      ;;
  esac
}

main "$@"
