#!/usr/bin/env bash
# script-codex-gate.sh — the Codex binding for a canonical AskUserQuestion gate.
#
# Generated by codex/script-build-codex-skills.py from codex/gate-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Contract (DEV-CX-003 tool bindings, DEV-CX-011 leaf-owned gate relay, both
# approved-translation): a canonical human gate keeps its decision, its exact
# option set, its default and its resume point on Codex. This helper turns a gate
# into a structured envelope so those properties are machine-checkable rather than
# prose, and so a leaf thread can hand its gate to the root thread verbatim.
#
# It never decides anything itself. It emits the envelope, validates an answer
# against the declared option set, and fails closed when the active surface cannot
# hold the run at the gate.
#
# Usage:
#   script-codex-gate.sh --id <gate-id> --skill <skill> --question <text> \
#       --option <label> [--option <label> ...] [--default <label>] \
#       [--owner <thread-id>] [--answer <label>|__dismissed__]
#
# The answer channel is either --answer or MSG_CODEX_GATE_ANSWER. The available
# question surface is declared by MSG_CODEX_QUESTION_SURFACE:
#   structured (default) — the client offers a structured user-input tool
#   prose                — one concise question, the turn halts
#   none                 — no way to hold the run: the gate blocks (exit 3)
#
# Board channel (msg --gui). When the run was launched from the board's prompt
# console the server hands it a private gate directory as MSG_GUI_GATE_DIR, and
# the board becomes the question surface: this helper writes the gate to
# <dir>/<id>.ask.json and blocks until the board writes <dir>/<id>.answer, then
# feeds that answer through the same option validation as any other channel. The
# wait is bounded only by MSG_GUI_GATE_TIMEOUT (seconds; 0, the default, waits as
# long as the run lives) and a timeout blocks the gate — it is never defaulted.
#
# Exit codes (designed outcomes, not harness incidents):
#   0  envelope emitted (GATE_STATE=awaiting-answer) or answer accepted
#      (GATE_STATE=answered | GATE_STATE=dismissed-default)
#   3  GATE_STATE=blocked   — no surface can hold the run at a mandatory gate
#   4  GATE_STATE=rejected  — the answer is not one of the declared options
#   5  GATE_STATE=undecided — dismissal with no declared default
#   2  usage error

set -euo pipefail

id=""
skill=""
question=""
owner="root"
default=""
answer="${MSG_CODEX_GATE_ANSWER:-}"
options=()

while [ $# -gt 0 ]; do
  case "$1" in
    --id)       id="${2:-}"; shift 2 ;;
    --skill)    skill="${2:-}"; shift 2 ;;
    --question) question="${2:-}"; shift 2 ;;
    --option)   options+=("${2:-}"); shift 2 ;;
    --default)  default="${2:-}"; shift 2 ;;
    --owner)    owner="${2:-}"; shift 2 ;;
    --answer)   answer="${2:-}"; shift 2 ;;
    *) echo "script-codex-gate.sh: unknown argument: $1" >&2; exit 2 ;;
  esac
done

[ -n "$id" ] || { echo "script-codex-gate.sh: --id is required" >&2; exit 2; }
[ -n "$skill" ] || { echo "script-codex-gate.sh: --skill is required" >&2; exit 2; }
[ -n "$question" ] || { echo "script-codex-gate.sh: --question is required" >&2; exit 2; }
[ "${#options[@]}" -ge 1 ] || { echo "script-codex-gate.sh: at least one --option is required" >&2; exit 2; }

surface="${MSG_CODEX_QUESTION_SURFACE:-structured}"
case "$surface" in
  structured|prose|none) ;;
  *) echo "script-codex-gate.sh: unknown MSG_CODEX_QUESTION_SURFACE: $surface" >&2; exit 2 ;;
esac

if [ -n "$default" ]; then
  found=0
  for option in "${options[@]}"; do
    [ "$option" = "$default" ] && found=1
  done
  [ "$found" -eq 1 ] || { echo "script-codex-gate.sh: --default is not one of the options" >&2; exit 2; }
fi

emit_envelope() {
  printf 'GATE_ID=%s\n' "$id"
  printf 'GATE_SKILL=%s\n' "$skill"
  printf 'GATE_OWNER=%s\n' "$owner"
  printf 'GATE_SURFACE=%s\n' "$surface"
  printf 'GATE_QUESTION=%s\n' "$question"
  local option
  for option in "${options[@]}"; do
    printf 'GATE_OPTION=%s\n' "$option"
  done
  printf 'GATE_DEFAULT=%s\n' "$default"
}

# Fail closed. A mandatory gate is never downgraded to an assumption.
if [ "$surface" = "none" ]; then
  emit_envelope
  echo "GATE_STATE=blocked"
  echo "REASON=no question surface can hold the run at this gate; the mode blocks rather than proceeding"
  exit 3
fi

# The board channel. The gate is published as a file the server can render, and
# the run holds here — no option is chosen, widened or defaulted on its behalf.
gate_dir="${MSG_GUI_GATE_DIR:-}"

json_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

write_ask_file() {
  local tmp="$gate_dir/$id$ask_suffix.tmp" option first=1
  {
    printf '{"protocol":1,"id":"%s","skill":"%s","owner":"%s","surface":"gui","question":"%s","options":[' \
      "$(json_escape "$id")" "$(json_escape "$skill")" \
      "$(json_escape "$owner")" "$(json_escape "$question")"
    for option in "${options[@]}"; do
      [ "$first" -eq 1 ] || printf ','
      first=0
      printf '{"label":"%s","description":""}' "$(json_escape "$option")"
    done
    printf '],"default":"%s"}\n' "$(json_escape "$default")"
  } > "$tmp"
  mv "$tmp" "$gate_dir/$id$ask_suffix"
}

ask_suffix=".ask.json"
if [ -z "$answer" ] && [ -n "$gate_dir" ] && [ -d "$gate_dir" ]; then
  timeout="${MSG_GUI_GATE_TIMEOUT:-0}"
  case "$timeout" in
    ''|*[!0-9]*) echo "script-codex-gate.sh: MSG_GUI_GATE_TIMEOUT must be whole seconds" >&2; exit 2 ;;
  esac
  write_ask_file
  emit_envelope
  echo "GATE_CHANNEL=gui"
  echo "GATE_STATE=awaiting-answer"
  echo "GATE_RESUME=$skill:$id"
  waited=0
  while [ ! -f "$gate_dir/$id.answer" ]; do
    if [ "$timeout" -gt 0 ] && [ "$waited" -ge "$timeout" ]; then
      echo "GATE_STATE=blocked"
      echo "REASON=the board did not answer within MSG_GUI_GATE_TIMEOUT=${timeout}s; the gate blocks rather than assuming an answer"
      exit 3
    fi
    sleep 1
    waited=$((waited + 1))
  done
  answer="$(head -n 1 "$gate_dir/$id.answer" | tr -d '\r')"
fi

if [ -z "$answer" ]; then
  emit_envelope
  echo "GATE_STATE=awaiting-answer"
  echo "GATE_RESUME=$skill:$id"
  exit 0
fi

if [ "$answer" = "__dismissed__" ]; then
  emit_envelope
  if [ -z "$default" ]; then
    echo "GATE_STATE=undecided"
    echo "REASON=the gate was dismissed and declares no default; the run stops here"
    exit 5
  fi
  printf 'GATE_ANSWER=%s\n' "$default"
  echo "GATE_STATE=dismissed-default"
  echo "GATE_RESUME=$skill:$id"
  exit 0
fi

for option in "${options[@]}"; do
  if [ "$option" = "$answer" ]; then
    emit_envelope
    printf 'GATE_ANSWER=%s\n' "$answer"
    echo "GATE_STATE=answered"
    echo "GATE_RESUME=$skill:$id"
    exit 0
  fi
done

emit_envelope
printf 'GATE_REJECTED=%s\n' "$answer"
echo "GATE_STATE=rejected"
echo "REASON=the answer is not one of the declared options; the option set is never widened at answer time"
exit 4
