#!/usr/bin/env bash
# script-codex-agents-md.sh — Codex project-instruction initialization for msg.
#
# Generated by codex/script-build-codex-skills.py from codex/agents-md-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Contract (DEV-CX-004, approved-translation): `CLAUDE.md` stays the single source
# of project instructions. Codex discovers `AGENTS.md`, so a Codex-side init writes
# `AGENTS.md` as a thin pointer to `CLAUDE.md` — never a second copy of the rules.
# A human-authored `AGENTS.md` is never overwritten: the run stops instead of
# guessing which file wins.
#
# Usage:
#   script-codex-agents-md.sh <repo-root> [--check]
#
# Exit codes (designed outcomes, not harness incidents):
#   0  AGENTS_MD=created | AGENTS_MD=current | AGENTS_MD=updated | AGENTS_MD=would-create
#   3  AGENTS_MD=conflict     — a human-authored AGENTS.md exists; run stops
#   4  AGENTS_MD=no-canonical — CLAUDE.md is absent, so there is nothing to point at
#   2  usage error

set -euo pipefail

MARKER='<!-- msg:codex-agents-pointer v1 -->'

pointer_body() {
  cat <<'POINTER'
<!-- msg:codex-agents-pointer v1 -->
# Project instructions

The instructions for this repository live in **`CLAUDE.md`**. Read that file in
full and follow it; it is the single source of truth for every runtime, Codex
included. Nothing is duplicated here, so this file can never disagree with it.

The msg harness itself is installed under `.agents/skills/`. Each skill's
`SKILL.md` is a thin Codex adapter: it points at
`.agents/skills/shared/refs/codex-runtime.md` for the runtime bindings and at its
own `CLAUDE-SKILL.md` for the product contract.

If you are asked to change project instructions, edit `CLAUDE.md`. Regenerate
this pointer with `script-codex-agents-md.sh <repo-root>`; it is idempotent.
POINTER
}

main() {
  local root="${1:-}"
  local mode="${2:-}"
  [ -n "$root" ] || { echo "usage: $0 <repo-root> [--check]" >&2; exit 2; }
  [ -d "$root" ] || { echo "usage: $0 <repo-root> [--check] (not a directory)" >&2; exit 2; }
  case "$mode" in
    ""|--check) ;;
    *) echo "usage: $0 <repo-root> [--check]" >&2; exit 2 ;;
  esac

  local canonical="$root/CLAUDE.md"
  local pointer="$root/AGENTS.md"

  if [ ! -f "$canonical" ]; then
    echo "AGENTS_MD=no-canonical"
    echo "REASON=CLAUDE.md is absent; write the canonical project instructions first"
    exit 4
  fi

  if [ ! -f "$pointer" ]; then
    if [ "$mode" = "--check" ]; then
      echo "AGENTS_MD=would-create"
      exit 0
    fi
    pointer_body >"$pointer"
    echo "AGENTS_MD=created"
    exit 0
  fi

  if ! grep -qF "$MARKER" "$pointer"; then
    echo "AGENTS_MD=conflict"
    echo "REASON=AGENTS.md exists and was not generated by msg; CLAUDE.md and AGENTS.md must not disagree"
    echo "FIX=fold its content into CLAUDE.md and delete AGENTS.md, or keep it and skip Codex project init"
    exit 3
  fi

  if diff -q <(pointer_body) "$pointer" >/dev/null 2>&1; then
    echo "AGENTS_MD=current"
    exit 0
  fi

  if [ "$mode" = "--check" ]; then
    echo "AGENTS_MD=would-update"
    exit 0
  fi
  pointer_body >"$pointer"
  echo "AGENTS_MD=updated"
  exit 0
}

main "$@"
