#!/usr/bin/env bash
# script-codex-subagent.sh — child-thread lifecycle for msg on Codex.
#
# Generated by codex/script-build-codex-skills.py from codex/subagent-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Contract (DEV-CX-005, approved-translation; CX-G009): a Claude `Agent` packet is
# a Codex child thread. What must survive the translation is not the spawn syntax
# but the guarantees around it — one owner per packet, run IDs that never collide,
# a reviewer identity that is never a builder identity, and completed packets that
# are not re-run after an interruption.
#
# This helper decides nothing about the work. It records who owns what and refuses
# the four shapes that would quietly break the canonical contract:
#
#   * running an orchestration mode at all when child threads are unavailable
#     (the canonical alternative — the root reviewing its own build — is not a
#     degraded mode, it is a different product; the run blocks instead)
#   * a child thread reusing the root run ID, or two children sharing one ID
#   * a reviewer whose identity appears in the packet's builder list
#   * re-dispatching a packet the run state already records as done
#
# Usage:
#   script-codex-subagent.sh preflight [--requires independent-review]
#   script-codex-subagent.sh spawn --run-id <root> --thread <id> --packet <pid> \
#                                  --role orchestrator|planner|builder|reviewer \
#                                  [--ledger <file>] [--done <pid,...>]
#   script-codex-subagent.sh review-identity --ledger <file> --packet <pid>
#   script-codex-subagent.sh resume --ledger <file> [--done <pid,...>]
#
# Environment:
#   MSG_CODEX_SUBAGENTS   available (default) | unavailable
#   MSG_CODEX_MAX_THREADS declared concurrency width (default 4) — DEV-CX-013
#
# Exit codes (designed outcomes, not harness incidents):
#   0  the operation is allowed; the proof lines are on stdout
#   2  usage error
#   3  SUBAGENT_STATE=blocked — no child threads; an orchestration mode must not start
#   4  identity violation (duplicate thread, root ID reuse, or self-review)
#   5  resume violation (a completed packet was re-dispatched)

set -euo pipefail

LEDGER_DEFAULT=".msg-codex-threads.tsv"

usage_error() { echo "script-codex-subagent.sh: $1" >&2; exit 2; }

preflight() {
  local requires=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --requires) requires="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  local state="${MSG_CODEX_SUBAGENTS:-available}"
  local width="${MSG_CODEX_MAX_THREADS:-4}"
  case "$state" in
    available|unavailable) ;;
    *) usage_error "unknown MSG_CODEX_SUBAGENTS: $state" ;;
  esac
  printf 'SUBAGENTS=%s\n' "$state"
  printf 'DECLARED_WIDTH=%s\n' "$width"
  [ -n "$requires" ] && printf 'REQUIRES=%s\n' "$requires"
  if [ "$state" = "unavailable" ]; then
    echo "SUBAGENT_STATE=blocked"
    echo "REASON=child threads are unavailable; the canonical packet ownership and independent review cannot be honoured, and self-review is not an accepted substitute"
    exit 3
  fi
  echo "SUBAGENT_STATE=ready"
  exit 0
}

spawn() {
  local run_id="" thread="" packet="" role="" ledger="$LEDGER_DEFAULT" done_list=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --run-id) run_id="${2:-}"; shift 2 ;;
      --thread) thread="${2:-}"; shift 2 ;;
      --packet) packet="${2:-}"; shift 2 ;;
      --role) role="${2:-}"; shift 2 ;;
      --ledger) ledger="${2:-}"; shift 2 ;;
      --done) done_list="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$run_id" ] || usage_error "--run-id is required"
  [ -n "$thread" ] || usage_error "--thread is required"
  [ -n "$packet" ] || usage_error "--packet is required"
  case "$role" in
    orchestrator|planner|builder|reviewer) ;;
    *) usage_error "--role must be orchestrator, planner, builder or reviewer" ;;
  esac

  if [ "$thread" = "$run_id" ]; then
    echo "IDENTITY=violated"
    echo "REASON=the child thread reuses the root run ID; run IDs must stay disjoint"
    exit 4
  fi
  # Resume safety: the run state, not the model's recollection, decides what is
  # already finished. A packet recorded done is never dispatched a second time.
  if [ "$role" != "reviewer" ] && printf '%s' ",$done_list," | grep -qF ",$packet,"; then
    echo "RESUME_STATE=violated"
    printf 'REASON=packet %s is already recorded done; completed packets are not re-run\n' "$packet"
    exit 5
  fi
  if [ -f "$ledger" ] && awk -F'\t' -v t="$thread" '$2 == t { found = 1 } END { exit !found }' "$ledger"; then
    echo "IDENTITY=violated"
    echo "REASON=thread $thread is already registered; one packet, one owning thread"
    exit 4
  fi
  printf '%s\t%s\t%s\t%s\n' "$role" "$thread" "$packet" "$run_id" >> "$ledger"
  printf 'THREAD_SPAWNED=%s\n' "$thread"
  printf 'THREAD_ROLE=%s\n' "$role"
  printf 'THREAD_PACKET=%s\n' "$packet"
  printf 'THREAD_ROOT=%s\n' "$run_id"
  exit 0
}

review_identity() {
  local ledger="" packet=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --ledger) ledger="${2:-}"; shift 2 ;;
      --packet) packet="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$ledger" ] || usage_error "--ledger is required"
  [ -n "$packet" ] || usage_error "--packet is required"
  [ -f "$ledger" ] || usage_error "ledger not found: $ledger"

  local builders reviewers
  builders="$(awk -F'\t' -v p="$packet" '$1 == "builder" && $3 == p { print $2 }' "$ledger" | sort -u)"
  reviewers="$(awk -F'\t' -v p="$packet" '$1 == "reviewer" && $3 == p { print $2 }' "$ledger" | sort -u)"

  if [ -z "$reviewers" ]; then
    echo "INDEPENDENCE=missing"
    printf 'REASON=packet %s has no reviewer thread; coverage is repaired by spawning one, never by accepting the builder as reviewer\n' "$packet"
    exit 4
  fi
  local reviewer builder
  for reviewer in $reviewers; do
    for builder in $builders; do
      if [ "$reviewer" = "$builder" ]; then
        echo "INDEPENDENCE=violated"
        printf 'REASON=thread %s both built and reviewed packet %s\n' "$reviewer" "$packet"
        exit 4
      fi
    done
  done
  printf 'INDEPENDENCE=proven packet=%s\n' "$packet"
  for builder in $builders; do printf 'BUILT_BY=%s\n' "$builder"; done
  for reviewer in $reviewers; do printf 'REVIEWED_BY=%s\n' "$reviewer"; done
  exit 0
}

resume() {
  local ledger="" done_list=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --ledger) ledger="${2:-}"; shift 2 ;;
      --done) done_list="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$ledger" ] || usage_error "--ledger is required"
  [ -f "$ledger" ] || usage_error "ledger not found: $ledger"

  local packets packet skipped=0 dispatched=0
  packets="$(awk -F'\t' '$1 == "builder" || $1 == "planner" { print $3 }' "$ledger" | sort -u)"
  for packet in $packets; do
    if printf '%s' ",$done_list," | grep -qF ",$packet,"; then
      printf 'RESUME_SKIP=%s\n' "$packet"
      skipped=$((skipped + 1))
    else
      printf 'RESUME_DISPATCH=%s\n' "$packet"
      dispatched=$((dispatched + 1))
    fi
  done
  printf 'RESUME_SUMMARY skipped=%s dispatched=%s\n' "$skipped" "$dispatched"
  exit 0
}

main() {
  local mode="${1:-}"
  [ $# -gt 0 ] && shift || true
  case "$mode" in
    preflight) preflight "$@" ;;
    spawn) spawn "$@" ;;
    review-identity) review_identity "$@" ;;
    resume) resume "$@" ;;
    -h|--help) sed -n '2,45p' "$0" ;;
    *) usage_error "usage: $0 preflight|spawn|review-identity|resume [...]" ;;
  esac
}

main "$@"
