#!/usr/bin/env bash
# script-codex-invoke.sh — active-runtime invocation syntax for msg on Codex.
#
# Generated by codex/script-build-codex-skills.py from codex/invoke-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Contract (DEV-CX-001, approved-translation): only active-runtime invocation
# tokens change. `/plan-pm` becomes `$plan-pm`; mode flags, file paths, branch
# names, URLs and prose are untouched. Canonical payloads are never rewritten —
# their slash form is documentation of the other runtime. This helper exists so a
# skill emitting a menu, handoff or closing next step has one deterministic,
# testable way to produce the active runtime's syntax.
#
# Usage:
#   script-codex-invoke.sh names                 # the nine msg skill names
#   script-codex-invoke.sh translate <text...>   # translate the arguments
#   ... | script-codex-invoke.sh translate       # translate stdin
#
# Exit codes: 0 translated; 2 bad usage.

set -euo pipefail

SKILLS="msg intake plan-pm plan-review plan-em eng pre-merge merge emulate"

translate() {
  local pattern=""
  local name
  for name in $SKILLS; do
    if [ -z "$pattern" ]; then
      pattern="$name"
    else
      pattern="$pattern|$name"
    fi
  done
  # A slash form only counts as an invocation when it is not preceded by a word
  # character, another slash, a dot, a dash or a dollar (so paths such as
  # `features/merge` and already-translated `$merge` are left alone), and not
  # followed by one (so `/merge-base` is left alone).
  #
  # Two passes: a match consumes the separator that the next token needs as its
  # preceding-boundary anchor, so adjacent invocations (`run /eng /merge`) leave
  # every second token untranslated in a single pass. A missed token always sits
  # next to translated (`$`-prefixed) or non-matching text, so the second pass
  # sees its separator fresh and no third pass can ever find work.
  local expr="s#(^|[^A-Za-z0-9_/.$-])/($pattern)([^A-Za-z0-9_/.-]|\$)#\1\$\2\3#g"
  sed -E "$expr" | sed -E "$expr"
}

main() {
  local mode="${1:-}"
  case "$mode" in
    names)
      printf '%s\n' $SKILLS
      ;;
    translate)
      shift
      if [ $# -gt 0 ]; then
        printf '%s\n' "$*" | translate
      else
        translate
      fi
      ;;
    *)
      echo "usage: $0 <names|translate> [text]" >&2
      exit 2
      ;;
  esac
}

main "$@"
