#!/usr/bin/env bash
# script-codex-packet.sh — packet class, model tier and dispatch integrity on Codex.
#
# Generated by codex/script-build-codex-skills.py from codex/packet-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Two decided records meet here.
#
# DEV-CX-006 (approved-deviation) pins the model map: an Opus-tier packet runs on
# Codex `Terra`, a Sonnet-tier packet on `Luna`. That is a real difference in cost,
# latency and output quality, so it is never implicit — every packet emits the class
# it was assigned, the canonical tier that class requires, the Codex model that tier
# maps to, and the reason. The mapping is recorded per packet class in the report.
# An unknown class is a hard usage error: no packet silently inherits a tier, and
# nothing may lower a load-bearing packet's tier.
#
# DEV-CX-013 (approved-deviation) allows Codex scheduling and timing to differ but
# not the shape of the work. `check` therefore proves what the canonical protocol
# guarantees: packets stay file-disjoint, the wave decomposition emitted by
# `script-em-exec-collision.py` is authoritative, dependencies precede their
# dependants across wave barriers, and the declared width is never exceeded. Waves
# may be narrowed by a dependency sub-split; packets may never be merged, dropped,
# added or widened.
#
# Usage:
#   script-codex-packet.sh tier --class <class>
#   script-codex-packet.sh envelope --id <pid> --class <class> --owner <thread> \
#                                   --file <path> [--file <path> ...] \
#                                   [--dep <pid> ...] [--wave <n>]
#   script-codex-packet.sh check --dispatched <file> [--against <collision-output>] \
#                                [--max-width <n>]
#
# A `--dispatched` file carries one packet per line, blank lines and `#` comments
# ignored:
#
#   <id> class=<class> owner=<thread> files=<a,b> [deps=<x,y>] [wave=<n>] [parent=<pid>]
#
# `files=` is the packet's write scope for the classes that own writes (planner and
# both build classes) and its read scope for the rest, so a reviewer legitimately
# names the same paths as the packet it reviews.
#
# Packet classes and their canonical tiers:
#
#   orchestrator      opus   — decomposition, scheduling and consolidation judgement
#   planner           opus   — writes an engineering section and its tickets
#   synthesis         opus   — folds wave results into one manager summary
#   review            opus   — adversarial whole-change review
#   build-load-bearing opus  — load-bearing or uncertain implementation packet
#   build-mechanical  sonnet — scoped, mechanical implementation packet
#   check-mechanical  sonnet — deterministic checks and shape gates
#
# Exit codes:
#   0  allowed; the proof lines are on stdout
#   2  usage error (including an unknown packet class)
#   4  COLLISION — two dispatched packets share a file
#   5  DEPENDENCY — a dep is unknown, cyclic, or not in an earlier wave
#   6  DISPATCH — the script's packet set was dropped, merged or added to
#   7  WIDTH — a wave exceeds the declared concurrency width

set -euo pipefail

usage_error() { echo "script-codex-packet.sh: $1" >&2; exit 2; }

canonical_tier() {
  case "$1" in
    orchestrator|planner|synthesis|review|build-load-bearing) echo "opus" ;;
    build-mechanical|check-mechanical) echo "sonnet" ;;
    *) return 1 ;;
  esac
}

codex_model() {
  case "$1" in
    opus) echo "Terra" ;;
    sonnet) echo "Luna" ;;
    *) return 1 ;;
  esac
}

tier_reason() {
  case "$1" in
    orchestrator) echo "decomposition, tiering and consolidation are load-bearing judgement" ;;
    planner) echo "the plan and its tickets are the sole build spec" ;;
    synthesis) echo "synthesis states coverage and findings the user acts on" ;;
    review) echo "adversarial review must find what the builder missed" ;;
    build-load-bearing) echo "load-bearing or uncertain implementation" ;;
    build-mechanical) echo "scoped mechanical implementation inside a fixed spec" ;;
    check-mechanical) echo "deterministic check with a scripted verdict" ;;
    *) return 1 ;;
  esac
}

emit_tier() {
  local class="$1" tier model reason
  tier="$(canonical_tier "$class")" || usage_error "unknown packet class: $class"
  model="$(codex_model "$tier")"
  reason="$(tier_reason "$class")"
  printf 'PACKET_CLASS=%s\n' "$class"
  printf 'CANONICAL_TIER=%s\n' "$tier"
  printf 'CODEX_MODEL=%s\n' "$model"
  printf 'TIER_REASON=%s\n' "$reason"
  printf 'TIER_RECORD=DEV-CX-006 pinned map: opus->Terra, sonnet->Luna\n'
}

tier() {
  local class=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --class) class="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$class" ] || usage_error "--class is required"
  emit_tier "$class"
  exit 0
}

envelope() {
  local id="" class="" owner="" wave="" files=() deps=()
  while [ $# -gt 0 ]; do
    case "$1" in
      --id) id="${2:-}"; shift 2 ;;
      --class) class="${2:-}"; shift 2 ;;
      --owner) owner="${2:-}"; shift 2 ;;
      --file) files+=("${2:-}"); shift 2 ;;
      --dep) deps+=("${2:-}"); shift 2 ;;
      --wave) wave="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$id" ] || usage_error "--id is required"
  [ -n "$class" ] || usage_error "--class is required"
  [ -n "$owner" ] || usage_error "--owner is required"
  [ "${#files[@]}" -ge 1 ] || usage_error "--file is required at least once"

  printf 'PACKET_ID=%s\n' "$id"
  printf 'PACKET_OWNER=%s\n' "$owner"
  emit_tier "$class"
  [ -n "$wave" ] && printf 'PACKET_WAVE=%s\n' "$wave"
  local item
  for item in "${files[@]}"; do printf 'PACKET_FILE=%s\n' "$item"; done
  for item in "${deps[@]+"${deps[@]}"}"; do printf 'PACKET_DEP=%s\n' "$item"; done
  exit 0
}

check() {
  local dispatched="" against="" max_width=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --dispatched) dispatched="${2:-}"; shift 2 ;;
      --against) against="${2:-}"; shift 2 ;;
      --max-width) max_width="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$dispatched" ] || usage_error "--dispatched is required"
  [ -f "$dispatched" ] || usage_error "dispatched file not found: $dispatched"

  DISPATCHED_FILE="$dispatched" AGAINST_FILE="$against" MAX_WIDTH="$max_width" \
    python3 - <<'PY'
import os
import sys

dispatched = os.environ["DISPATCHED_FILE"]
against = os.environ.get("AGAINST_FILE") or ""
max_width = os.environ.get("MAX_WIDTH") or ""

TIERS = {
    "orchestrator": "opus",
    "planner": "opus",
    "synthesis": "opus",
    "review": "opus",
    "build-load-bearing": "opus",
    "build-mechanical": "sonnet",
    "check-mechanical": "sonnet",
}
MODELS = {"opus": "Terra", "sonnet": "Luna"}


def die(code, state, reason):
    print(f"DISPATCH_STATE={state}")
    print(f"REASON={reason}")
    sys.exit(code)


packets = []
for raw in open(dispatched, encoding="utf-8"):
    line = raw.strip()
    if not line or line.startswith("#"):
        continue
    parts = line.split()
    record = {"id": parts[0], "files": [], "deps": [], "wave": None, "parent": None}
    for field in parts[1:]:
        if "=" not in field:
            die(2, "malformed", f"packet {record['id']}: field without a value: {field}")
        key, value = field.split("=", 1)
        if key == "files":
            record["files"] = [v for v in value.split(",") if v]
        elif key == "deps":
            record["deps"] = [v for v in value.split(",") if v]
        elif key == "wave":
            record["wave"] = int(value)
        elif key in ("class", "owner", "parent"):
            record[key] = value
        else:
            die(2, "malformed", f"packet {record['id']}: unknown field: {key}")
    if "class" not in record or record["class"] not in TIERS:
        die(2, "malformed", f"packet {record['id']}: unknown or missing class")
    if not record["files"]:
        die(2, "malformed", f"packet {record['id']}: no files")
    packets.append(record)

if not packets:
    die(2, "malformed", "no packets were dispatched")

ids = [p["id"] for p in packets]
if len(set(ids)) != len(ids):
    die(6, "duplicate", "the same packet id was dispatched more than once")

# File disjointness — the guarantee that makes concurrency safe at all. It binds
# the packet classes that own writes; a reviewer, checker, orchestrator or
# synthesis packet reads the same paths by design and owns none of them.
WRITERS = {"planner", "build-load-bearing", "build-mechanical"}
owner_of = {}
for packet in packets:
    if packet["class"] not in WRITERS:
        continue
    for path in packet["files"]:
        if path in owner_of:
            print(f"COLLISION {owner_of[path]} {packet['id']} {path}")
            die(4, "collision", "two dispatched packets own the same file")
        owner_of[path] = packet["id"]

# Dependency integrity and wave barriers.
known = set(ids)
wave_of = {p["id"]: p["wave"] for p in packets}
for packet in packets:
    for dep in packet["deps"]:
        if dep not in known:
            die(5, "dependency", f"packet {packet['id']} depends on unknown packet {dep}")
        if dep == packet["id"]:
            die(5, "dependency", f"packet {packet['id']} depends on itself")
        if wave_of[packet["id"]] is not None and wave_of[dep] is not None:
            if wave_of[dep] >= wave_of[packet["id"]]:
                die(
                    5,
                    "dependency",
                    f"packet {packet['id']} runs in wave {wave_of[packet['id']]} "
                    f"but depends on {dep} in wave {wave_of[dep]}",
                )

# Cycle detection over the declared DAG.
state = {}
def visit(node, chain):
    if state.get(node) == "done":
        return
    if state.get(node) == "open":
        die(5, "dependency", "dependency cycle: " + " -> ".join(chain + [node]))
    state[node] = "open"
    for dep in next(p for p in packets if p["id"] == node)["deps"]:
        visit(dep, chain + [node])
    state[node] = "done"

for packet in packets:
    visit(packet["id"], [])

# Width: Codex may finish a wave in a different order, never run a wider one.
waves = {}
for packet in packets:
    if packet["wave"] is not None:
        waves.setdefault(packet["wave"], []).append(packet["id"])
if max_width:
    limit = int(max_width)
    for wave in sorted(waves):
        if len(waves[wave]) > limit:
            die(7, "width", f"wave {wave} dispatches {len(waves[wave])} packets over the declared width {limit}")

# The collision script's decomposition is authoritative. A dispatched packet is
# either one of its packets or a declared dependency sub-split of one; every
# script packet must be covered exactly once.
if against:
    script_packets = []
    for raw in open(against, encoding="utf-8"):
        if raw.startswith("PACKET "):
            script_packets.append(raw.split()[1])
    if not script_packets:
        die(6, "dispatch", f"no PACKET lines found in {against}")
    covered = {}
    for packet in packets:
        source = packet["parent"] or packet["id"]
        if source not in script_packets:
            die(6, "dispatch", f"packet {packet['id']} is not in the collision script's decomposition")
        covered.setdefault(source, []).append(packet["id"])
    missing = [p for p in script_packets if p not in covered]
    if missing:
        die(6, "dispatch", "script packets were dropped or merged away: " + ",".join(missing))
    for source in script_packets:
        children = covered[source]
        if len(children) > 1:
            print(f"SUBSPLIT {source} into={','.join(sorted(children))}")
    print(f"DISPATCH_MATCHES_SCRIPT packets={len(script_packets)}")

for packet in packets:
    tier = TIERS[packet["class"]]
    print(
        f"PACKET {packet['id']} class={packet['class']} tier={tier} "
        f"model={MODELS[tier]} owner={packet.get('owner', '-')} files={len(packet['files'])}"
    )
for wave in sorted(waves):
    print(f"WAVE {wave} packets={','.join(waves[wave])}")
print(f"DISPATCH_OK packets={len(packets)} waves={len(waves)}")
PY
  exit $?
}

main() {
  local mode="${1:-}"
  [ $# -gt 0 ] && shift || true
  case "$mode" in
    tier) tier "$@" ;;
    envelope) envelope "$@" ;;
    check) check "$@" ;;
    -h|--help) sed -n '2,60p' "$0" ;;
    *) usage_error "usage: $0 tier|envelope|check [...]" ;;
  esac
}

main "$@"
