#!/usr/bin/env bash
# script-codex-release.sh — the release-gate sequencer for merge on Codex.
#
# Generated by codex/script-build-codex-skills.py from codex/release-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Contract (DEV-CX-003 and DEV-CX-005, both approved-translation; AMB-CX-005,
# decided): merge's safety is not in any single check — it is in the ORDER. The
# lock is read early so a colliding ship fails fast, and taken late so it is held
# only across the part that mutates production. The two production confirmations
# are two separate human decisions, not one asked twice. A staging sign-off is
# only worth anything if it names the commit that was actually tested. Rollback is
# offered and then decided; it is never something the run does on its own.
#
# On Claude that order is prose the model follows. On Codex the same prose is the
# same contract, but nothing about a Codex run makes the order checkable — so this
# helper makes the run's own event journal the evidence. It decides nothing and
# performs nothing: it reads what a run recorded and refuses every ordering that
# would keep the checks while losing the guarantee.
#
# Journal format — one tab-separated line per event, in the order they happened:
#
#   <event>\t<owner>\t<detail>
#
#   events   lock-check · lock-acquire · lock-release · ci:green · ci:red ·
#            merge · deploy · verify · ship · stamp · rollback-offer ·
#            rollback-exec · gate:signoff · gate:confirm-1 · gate:confirm-2 ·
#            gate:human-test · gate:rollback
#   owner    the thread that recorded it; every `gate:` event must be owned by
#            `root` — a nested Codex child thread never asks a human or infers
#            an approval, exactly as no nested Claude agent may
#   detail   the event's payload: a sha for `verify`/`gate:signoff`, the
#            attested text for a confirmation, `approve`/`decline`/`cancel` for
#            a decision
#
# Usage:
#   script-codex-release.sh sequence --journal <file> \
#       --mode staging|production [--flow staged|direct]
#
# Exit codes (designed outcomes, not harness incidents):
#   0  RELEASE_STATE=ok | cancelled — the recorded order honours every gate
#   2  usage error
#   3  RELEASE_STATE=lock-unchecked   — the lock was not read before the gates
#   4  RELEASE_STATE=lock-early       — the lock was taken before the gates cleared
#   5  RELEASE_STATE=gate-missing | gate-out-of-order | gate-collapsed |
#                    gate-misowned | cancel-ignored | ci-not-green
#   6  RELEASE_STATE=signoff-unpinned — the sign-off does not name the tested commit
#   7  RELEASE_STATE=rollback-auto    — a rollback ran without being offered and decided
#   8  RELEASE_STATE=lock-leaked      — the run ended still holding the lock

set -euo pipefail

usage_error() { echo "script-codex-release.sh: $1" >&2; exit 2; }

refuse() {
  local state="$1" reason="$2" code="$3"
  printf 'RELEASE_STATE=%s\n' "$state"
  printf 'REASON=%s\n' "$reason"
  exit "$code"
}

KNOWN_EVENTS="lock-check lock-acquire lock-release ci:green ci:red merge deploy verify ship stamp rollback-offer rollback-exec gate:signoff gate:confirm-1 gate:confirm-2 gate:human-test gate:rollback"
ADVANCING_EVENTS="lock-acquire merge deploy ship stamp"

events=()
owners=()
details=()

# first index of an event, or -1
index_of() {
  local want="$1" i
  for i in "${!events[@]}"; do
    [ "${events[$i]}" = "$want" ] && { printf '%s\n' "$i"; return 0; }
  done
  printf '%s\n' "-1"
}

detail_of() {
  local want="$1" i
  i="$(index_of "$want")"
  [ "$i" = "-1" ] || printf '%s\n' "${details[$i]}"
}

sequence() {
  local journal="" mode="" flow="staged"
  while [ $# -gt 0 ]; do
    case "$1" in
      --journal) journal="${2:-}"; shift 2 ;;
      --mode)    mode="${2:-}"; shift 2 ;;
      --flow)    flow="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$journal" ] || usage_error "--journal is required"
  [ -f "$journal" ] || usage_error "journal not found: $journal"
  case "$mode" in
    staging|production) ;;
    *) usage_error "--mode must be staging or production" ;;
  esac
  case "$flow" in
    staged|direct) ;;
    *) usage_error "--flow must be staged or direct" ;;
  esac

  local event owner detail known candidate
  while IFS=$'\t' read -r event owner detail || [ -n "${event:-}" ]; do
    [ -n "${event:-}" ] || continue
    case "$event" in \#*) continue ;; esac
    known=0
    for candidate in $KNOWN_EVENTS; do
      [ "$candidate" = "$event" ] && known=1
    done
    [ "$known" -eq 1 ] || usage_error "unknown journal event: $event"
    events+=("$event")
    owners+=("${owner:-}")
    details+=("${detail:-}")
  done < "$journal"
  [ "${#events[@]}" -ge 1 ] || usage_error "journal is empty"

  local i
  # 1. Gate ownership. A gate answered anywhere but the root thread is a gate the
  #    human never saw in the place the contract puts it.
  for i in "${!events[@]}"; do
    case "${events[$i]}" in
      gate:*)
        [ "${owners[$i]}" = "root" ] || refuse gate-misowned \
          "gate ${events[$i]} was recorded by ${owners[$i]}; every merge gate is owned by the main thread, never by a nested agent" 5 ;;
    esac
  done

  # 2. A cancelled decision ends the run. Anything that advances the ship after it
  #    means a human said no and the run continued anyway.
  local cancelled=-1
  for i in "${!events[@]}"; do
    case "${events[$i]}" in
      gate:*) [ "${details[$i]}" = "cancel" ] && { cancelled="$i"; break; } ;;
    esac
  done
  if [ "$cancelled" -ge 0 ]; then
    for i in "${!events[@]}"; do
      [ "$i" -gt "$cancelled" ] || continue
      for candidate in $ADVANCING_EVENTS; do
        [ "$candidate" = "${events[$i]}" ] && refuse cancel-ignored \
          "${events[$cancelled]} was cancelled, then ${events[$i]} still ran; a cancelled confirmation stops the ship" 5
      done
    done
  fi

  local i_merge i_ship i_acquire i_release i_lock_check
  i_merge="$(index_of merge)"
  i_ship="$(index_of ship)"
  i_acquire="$(index_of lock-acquire)"
  i_release="$(index_of lock-release)"
  i_lock_check="$(index_of lock-check)"

  # 3. Lock read first (phase 1, fail fast) — before any human is asked to decide
  #    and before anything merges.
  local i_first_gate=-1
  for i in "${!events[@]}"; do
    case "${events[$i]}" in gate:*) i_first_gate="$i"; break ;; esac
  done
  if [ "$i_merge" != "-1" ] || [ "$i_first_gate" != "-1" ]; then
    [ "$i_lock_check" != "-1" ] || refuse lock-unchecked \
      "the release lock was never read; a colliding ship must fail before the run asks a human anything" 3
    if [ "$i_first_gate" != "-1" ] && [ "$i_lock_check" -gt "$i_first_gate" ]; then
      refuse lock-unchecked \
        "the lock was read after the first gate; the check belongs to phase 1 so a contended run fails fast" 3
    fi
    if [ "$i_merge" != "-1" ] && [ "$i_lock_check" -gt "$i_merge" ]; then
      refuse lock-unchecked "the lock was read after the merge had already happened" 3
    fi
  fi

  # 4. Required gates, in the order the flow demands.
  local required=""
  case "$mode:$flow" in
    staging:*)           required="gate:signoff" ;;
    production:staged)   required="gate:confirm-1 gate:confirm-2" ;;
    production:direct)   required="gate:confirm-1 gate:human-test gate:confirm-2" ;;
  esac

  local gate previous=-1 idx
  if [ "$i_merge" != "-1" ] || [ "$i_ship" != "-1" ] || [ "$cancelled" -lt 0 ]; then
    for gate in $required; do
      idx="$(index_of "$gate")"
      if [ "$idx" = "-1" ]; then
        # A run cancelled at an earlier gate legitimately never reaches the later ones.
        [ "$cancelled" -ge 0 ] && continue
        refuse gate-missing "$gate never happened; it is mandatory for a $mode $flow release" 5
      fi
      if [ "$previous" -ge 0 ] && [ "$idx" -lt "$previous" ]; then
        refuse gate-out-of-order "$gate was recorded before the gate that must precede it" 5
      fi
      previous="$idx"
    done
  fi

  # 5. Two confirmations means two decisions. Identical attestations are one
  #    decision recorded twice.
  if [ "$mode" = "production" ]; then
    local c1 c2
    c1="$(detail_of gate:confirm-1)"
    c2="$(detail_of gate:confirm-2)"
    if [ -n "$c1" ] && [ -n "$c2" ] && [ "$c1" = "$c2" ]; then
      refuse gate-collapsed \
        "both production confirmations carry the same attestation; the second confirmation is a separate decision, not a repeat" 5
    fi
  fi

  # 6. Green CI before any merge, and never a red one standing.
  if [ "$i_merge" != "-1" ]; then
    local ci_state="" ci_index=-1
    for i in "${!events[@]}"; do
      [ "$i" -lt "$i_merge" ] || break
      case "${events[$i]}" in ci:green) ci_state="green"; ci_index="$i" ;; ci:red) ci_state="red"; ci_index="$i" ;; esac
    done
    [ "$ci_state" = "green" ] || refuse ci-not-green \
      "the merge ran with CI recorded as '${ci_state:-nothing}'; an absent or red check set is never read as green" 5
    : "$ci_index"
  fi

  # 7. A staging sign-off certifies one commit: the one that was deployed and
  #    tested. A sign-off naming anything else certifies nothing.
  if [ "$mode" = "staging" ]; then
    local i_verify i_signoff
    i_verify="$(index_of verify)"
    i_signoff="$(index_of gate:signoff)"
    if [ "$i_signoff" != "-1" ]; then
      [ "$i_verify" != "-1" ] || refuse signoff-unpinned \
        "the sign-off was taken without a verified deployment to pin it to" 6
      [ "$i_signoff" -gt "$i_verify" ] || refuse signoff-unpinned \
        "the sign-off was recorded before the deployment it certifies was verified" 6
      if [ "${details[$i_signoff]}" != "${details[$i_verify]}" ]; then
        refuse signoff-unpinned \
          "the sign-off names ${details[$i_signoff]} but the verified staging tip was ${details[$i_verify]}" 6
      fi
    fi
  fi

  # 8. The lock is taken last, after every human gate has cleared.
  if [ "$i_acquire" != "-1" ]; then
    [ "$mode" = "production" ] || refuse lock-early \
      "a staging advance checks the production release lock but never takes it" 4
    for gate in $required; do
      idx="$(index_of "$gate")"
      [ "$idx" = "-1" ] && continue
      [ "$i_acquire" -gt "$idx" ] || refuse lock-early \
        "the lock was acquired before $gate cleared; it is held only across the production mutation" 4
    done
    [ "$i_merge" = "-1" ] || [ "$i_acquire" -lt "$i_merge" ] || refuse lock-early \
      "the merge ran before the lock was acquired" 4
  elif [ "$mode" = "production" ] && [ "$i_merge" != "-1" ]; then
    refuse lock-early "the production merge ran without ever acquiring the release lock" 4
  fi

  # 9. Rollback is offered, decided, and only then run.
  local i_offer i_exec i_decision
  i_offer="$(index_of rollback-offer)"
  i_exec="$(index_of rollback-exec)"
  i_decision="$(index_of gate:rollback)"
  if [ "$i_exec" != "-1" ]; then
    [ "$i_offer" != "-1" ] && [ "$i_offer" -lt "$i_exec" ] || refuse rollback-auto \
      "a rollback ran without being offered; the lever is always presented, never pulled automatically" 7
    [ "$i_decision" != "-1" ] && [ "$i_decision" -lt "$i_exec" ] || refuse rollback-auto \
      "a rollback ran without a recorded human decision" 7
    [ "$(detail_of gate:rollback)" = "approve" ] || refuse rollback-auto \
      "a rollback ran although the recorded decision was '$(detail_of gate:rollback)'" 7
  fi

  # 10. Every terminal path releases the lock, including the ones that refuse.
  if [ "$i_acquire" != "-1" ]; then
    [ "$i_release" != "-1" ] && [ "$i_release" -gt "$i_acquire" ] || refuse lock-leaked \
      "the run ended still holding the release lock; every terminal path releases it" 8
  fi

  for i in "${!events[@]}"; do
    printf 'RELEASE_EVENT=%s\n' "${events[$i]}"
  done
  printf 'RELEASE_MODE=%s\n' "$mode"
  printf 'RELEASE_FLOW=%s\n' "$flow"
  printf 'RELEASE_GATES=%s\n' "$(printf '%s\n' $required | sed '/^$/d' | wc -l | tr -d ' ')"
  if [ "$cancelled" -ge 0 ]; then
    printf 'RELEASE_CANCELLED_AT=%s\n' "${events[$cancelled]}"
    echo "RELEASE_STATE=cancelled"
    exit 0
  fi
  echo "RELEASE_STATE=ok"
  exit 0
}

main() {
  local mode="${1:-}"
  [ $# -gt 0 ] && shift || true
  case "$mode" in
    sequence) sequence "$@" ;;
    -h|--help) sed -n '2,50p' "$0" ;;
    *) usage_error "usage: $0 sequence --journal <file> --mode staging|production [--flow staged|direct]" ;;
  esac
}

main "$@"
