#!/usr/bin/env python3
"""Deterministic generator for the Codex (.agents) side of the msg harness.

Reads the canonical Claude tree (`.claude/skills/**`, `.claude/scripts/**`, as
tracked by git) and emits the Codex mirror under `.agents/`, plus a generation
manifest at `codex/generation-manifest.json`.

Guarantees
----------
* **Read-only against Claude.** Nothing under `.claude/`, `install.sh`,
  `package.json`, `evals/codex/baselines/` or `evals/codex/verify_phase0*.py` is
  opened for writing. (CX-G003)
* **Byte-deterministic.** No timestamps, no absolute paths, no environment
  values, no dict-iteration order reach a generated byte. Running twice on the
  same input produces the same tree. (CX-G002)
* **Hand-authored files are protected.** The ten compatibility maps,
  `codex-runtime.md` and the pre-existing `harness-map.md` are never written and
  never pruned.
* **Prune is manifest-scoped.** Only paths this generator previously emitted are
  removed when they stop being emitted. Unknown files under `.agents/` are left
  alone and reported.

Usage:
  python3 codex/script-build-codex-skills.py [--check]

`--check` performs no writes and exits 1 if the tree is not already current.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

CANONICAL_SKILL_ROOT = ".claude/skills"
CANONICAL_SCRIPT_ROOT = ".claude/scripts"
CODEX_SKILL_ROOT = ".agents/skills"
CODEX_SCRIPT_ROOT = ".agents/scripts"

SHARED = "shared"
EXPECTED_SKILL_COUNT = 9

ADAPTER_TEMPLATE = "codex/adapter-template.md"
MANIFEST = "codex/generation-manifest.json"

# Codex-native runtime helpers: hand-authored under codex/, emitted verbatim into
# the Codex script root so a repo-local Codex session finds them beside the
# mirrored canonical helpers. Each one implements a decided DEV-CX record.
CODEX_NATIVE_SCRIPTS = {
    "codex/resolver-template.sh": f"{CODEX_SCRIPT_ROOT}/script-codex-resolve.sh",
    "codex/agents-md-template.sh": f"{CODEX_SCRIPT_ROOT}/script-codex-agents-md.sh",
    "codex/gate-template.sh": f"{CODEX_SCRIPT_ROOT}/script-codex-gate.sh",
    "codex/invoke-template.sh": f"{CODEX_SCRIPT_ROOT}/script-codex-invoke.sh",
    "codex/packet-template.sh": f"{CODEX_SCRIPT_ROOT}/script-codex-packet.sh",
    "codex/relay-template.sh": f"{CODEX_SCRIPT_ROOT}/script-codex-relay.sh",
    "codex/subagent-template.sh": f"{CODEX_SCRIPT_ROOT}/script-codex-subagent.sh",
}

# GUI runtime variant (DEV-CX-014). The mirrored board stays byte-identical to the
# canonical one; the Codex variant is generated beside it from the same source by
# invocation-token translation plus the declared copy substitutions, so the two can
# never drift apart by hand.
GUI_SOURCE_DIR = f"{CANONICAL_SKILL_ROOT}/msg/refs/gui"
GUI_VARIANT_DIR = f"{CODEX_SKILL_ROOT}/msg/refs/gui/codex"
GUI_COPY_MAP = "codex/gui-codex-copy.json"
GUI_VARIANT_FILES = ("index.html", "styles.css")

CANONICAL_PAYLOAD_NAME = "CLAUDE-SKILL.md"
ADAPTER_NAME = "SKILL.md"
METADATA_NAME = "agents/openai.yaml"

# Hand-authored Codex files. Never generated, never pruned.
PROTECTED_SUFFIXES = ("refs/compatibility-map.md",)
PROTECTED_PATHS = frozenset(
    {
        f"{CODEX_SKILL_ROOT}/{SHARED}/refs/codex-runtime.md",
        f"{CODEX_SKILL_ROOT}/{SHARED}/refs/harness-map.md",
    }
)

DESCRIPTION_WRAP = 76
DESCRIPTION_INDENT = "  "


# --------------------------------------------------------------------------- #
# canonical input discovery
# --------------------------------------------------------------------------- #


def git_files(*patterns: str) -> list[str]:
    """Tracked paths, sorted. git ls-files output order is already sorted, but we
    sort again so the generator never depends on git's collation."""
    result = subprocess.run(
        ["git", "ls-files", "-z", "--", *patterns],
        cwd=REPO,
        check=True,
        capture_output=True,
    )
    return sorted(p for p in result.stdout.decode().split("\0") if p)


def discover_skills(skill_files: list[str]) -> list[str]:
    names = sorted({path.split("/")[2] for path in skill_files})
    production = [name for name in names if name != SHARED]
    if SHARED not in names:
        raise SystemExit("canonical shared tree is missing")
    if len(production) != EXPECTED_SKILL_COUNT:
        raise SystemExit(
            f"expected {EXPECTED_SKILL_COUNT} production skills, discovered "
            f"{len(production)}: {production}"
        )
    return production


# --------------------------------------------------------------------------- #
# canonical frontmatter
# --------------------------------------------------------------------------- #


def split_frontmatter(text: str) -> tuple[list[str], str]:
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise SystemExit("canonical SKILL.md has no opening frontmatter delimiter")
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return lines[1:index], "\n".join(lines[index + 1 :])
    raise SystemExit("canonical SKILL.md has no closing frontmatter delimiter")


def frontmatter_scalar(meta: list[str], key: str) -> str:
    """Read a scalar or folded/literal block scalar out of flat frontmatter."""
    prefix = f"{key}:"
    for index, line in enumerate(meta):
        if not line.startswith(prefix):
            continue
        inline = line[len(prefix) :].strip()
        if inline and inline not in (">", "|", ">-", "|-", ">+", "|+"):
            return inline
        block: list[str] = []
        for candidate in meta[index + 1 :]:
            if candidate.strip() and not candidate.startswith((" ", "\t")):
                break
            block.append(candidate.strip())
        return " ".join(part for part in block if part)
    raise SystemExit(f"canonical frontmatter is missing '{key}'")


# --------------------------------------------------------------------------- #
# invocation translation (DEV-CX-001, approved-translation)
# --------------------------------------------------------------------------- #


def invocation_pattern(skills: list[str]) -> re.Pattern[str]:
    alternatives = "|".join(re.escape(name) for name in sorted(skills, key=len, reverse=True))
    return re.compile(rf"(?<![\w/.\-$])/({alternatives})(?![\w/.\-])")


def to_codex_invocation(text: str, pattern: re.Pattern[str]) -> str:
    """Rewrite active-runtime `/name` tokens to `$name`.

    Applied to adapter-facing text only. Canonical payloads are never touched:
    the compensating control on DEV-CX-001 requires the payload to stay
    byte-identical to the Claude source.
    """
    return pattern.sub(r"$\1", text)


# --------------------------------------------------------------------------- #
# deterministic text shaping
# --------------------------------------------------------------------------- #


def normalize_description(raw: str) -> str:
    return " ".join(raw.split())


def wrap(text: str, width: int, indent: str) -> str:
    words = text.split(" ")
    lines: list[str] = []
    current = indent
    for word in words:
        candidate = word if current == indent else f"{current} {word}"
        if current != indent and len(candidate) > width:
            lines.append(current)
            current = indent + word
        else:
            current = indent + word if current == indent else candidate
    lines.append(current)
    return "\n".join(lines)


def yaml_single_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# --------------------------------------------------------------------------- #
# output construction
# --------------------------------------------------------------------------- #


class Output:
    __slots__ = ("data", "mode", "source", "kind")

    def __init__(self, data: bytes, mode: int, source: str | None, kind: str) -> None:
        self.data = data
        self.mode = mode
        self.source = source
        self.kind = kind


def read_source(path: str) -> tuple[bytes, int]:
    full = REPO / path
    return full.read_bytes(), (0o755 if os.access(full, os.X_OK) else 0o644)


def build_adapter(
    skill: str,
    canonical_path: str,
    canonical_bytes: bytes,
    template: str,
    pattern: re.Pattern[str],
) -> bytes:
    meta, _ = split_frontmatter(canonical_bytes.decode())
    description = to_codex_invocation(
        normalize_description(frontmatter_scalar(meta, "description")), pattern
    )
    canonical_name = frontmatter_scalar(meta, "name")
    if canonical_name != skill:
        raise SystemExit(f"{canonical_path}: frontmatter name '{canonical_name}' != '{skill}'")
    rendered = (
        template.replace("{{DESCRIPTION}}", wrap(description, DESCRIPTION_WRAP, DESCRIPTION_INDENT))
        .replace("{{CANONICAL_DIGEST}}", sha256(canonical_bytes))
        .replace("{{CANONICAL}}", canonical_path)
        .replace("{{NAME}}", skill)
    )
    if "{{" in rendered:
        raise SystemExit(f"{skill}: adapter template has unsubstituted placeholders")
    return rendered.encode()


def build_metadata(
    skill: str,
    canonical_path: str,
    canonical_bytes: bytes,
    description: str,
) -> bytes:
    lines = [
        "# Generated by codex/script-build-codex-skills.py — do not hand-edit.",
        f"name: {skill}",
        f"description: {yaml_single_quote(description)}",
        "entrypoint: SKILL.md",
        "canonical:",
        f"  runtime: claude-code",
        f"  source: {canonical_path}",
        f"  payload: {CANONICAL_PAYLOAD_NAME}",
        f"  digest: sha256:{sha256(canonical_bytes)}",
        "compatibility_map: refs/compatibility-map.md",
        "runtime_contract: ../shared/refs/codex-runtime.md",
        "",
    ]
    return "\n".join(lines).encode()


def build_gui_variant(pattern: re.Pattern[str]) -> dict[str, Output]:
    """Generate the Codex board variant (DEV-CX-014).

    `styles.css` is copied byte-for-byte; `index.html` gets exactly two classes of
    change: the mechanical `/skill` to `$skill` invocation translation, and the
    copy substitutions declared in `codex/gui-codex-copy.json`. A declared
    substitution that no longer matches its source is a hard failure — the
    difference list may never silently go stale.
    """
    copy_map = json.loads((REPO / GUI_COPY_MAP).read_text())
    outputs: dict[str, Output] = {}

    for name in GUI_VARIANT_FILES:
        source = f"{GUI_SOURCE_DIR}/{name}"
        data, mode = read_source(source)
        if name.endswith(".html"):
            text = data.decode()
            for rule in copy_map["substitutions"]:
                found = text.count(rule["from"])
                minimum = int(rule.get("min_occurrences", 1))
                if found < minimum:
                    raise SystemExit(
                        f"{GUI_COPY_MAP}: substitution {rule['from']!r} matched {found} times, "
                        f"expected at least {minimum}"
                    )
                text = text.replace(rule["from"], rule["to"])
            data = to_codex_invocation(text, pattern).encode()
        outputs[f"{GUI_VARIANT_DIR}/{name}"] = Output(data, mode, source, "codex-native")
    return outputs


def collect_outputs(skills: list[str]) -> dict[str, Output]:
    outputs: dict[str, Output] = {}
    pattern = invocation_pattern(skills)
    template = (REPO / ADAPTER_TEMPLATE).read_text()

    skill_files = git_files(f"{CANONICAL_SKILL_ROOT}/**")
    script_files = git_files(f"{CANONICAL_SCRIPT_ROOT}/**")

    for path in skill_files:
        rel = path[len(CANONICAL_SKILL_ROOT) + 1 :]
        owner, _, inner = rel.partition("/")
        data, mode = read_source(path)
        if owner == SHARED:
            destination = f"{CODEX_SKILL_ROOT}/{SHARED}/{inner}"
        elif inner == ADAPTER_NAME:
            destination = f"{CODEX_SKILL_ROOT}/{owner}/{CANONICAL_PAYLOAD_NAME}"
        else:
            destination = f"{CODEX_SKILL_ROOT}/{owner}/{inner}"
        outputs[destination] = Output(data, mode, path, "canonical-copy")

    for skill in skills:
        canonical_path = f"{CANONICAL_SKILL_ROOT}/{skill}/{ADAPTER_NAME}"
        canonical_bytes, _ = read_source(canonical_path)
        meta, _ = split_frontmatter(canonical_bytes.decode())
        description = to_codex_invocation(
            normalize_description(frontmatter_scalar(meta, "description")), pattern
        )
        outputs[f"{CODEX_SKILL_ROOT}/{skill}/{ADAPTER_NAME}"] = Output(
            build_adapter(skill, canonical_path, canonical_bytes, template, pattern),
            0o644,
            canonical_path,
            "adapter",
        )
        outputs[f"{CODEX_SKILL_ROOT}/{skill}/{METADATA_NAME}"] = Output(
            build_metadata(skill, canonical_path, canonical_bytes, description),
            0o644,
            canonical_path,
            "metadata",
        )

    for path in script_files:
        data, mode = read_source(path)
        destination = f"{CODEX_SCRIPT_ROOT}/{path[len(CANONICAL_SCRIPT_ROOT) + 1 :]}"
        outputs[destination] = Output(data, mode, path, "canonical-copy")

    for source, destination in sorted(CODEX_NATIVE_SCRIPTS.items()):
        data, _ = read_source(source)
        outputs[destination] = Output(data, 0o755, source, "codex-native")

    for destination, output in build_gui_variant(pattern).items():
        outputs[destination] = output

    for destination in outputs:
        if is_protected(destination):
            raise SystemExit(f"generator would overwrite a protected file: {destination}")
    return outputs


def is_protected(path: str) -> bool:
    return path in PROTECTED_PATHS or path.endswith(PROTECTED_SUFFIXES)


# --------------------------------------------------------------------------- #
# manifest and apply
# --------------------------------------------------------------------------- #


def build_manifest(outputs: dict[str, Output], skills: list[str]) -> bytes:
    files = [
        {
            "path": path,
            "kind": outputs[path].kind,
            "source": outputs[path].source,
            "mode": f"{outputs[path].mode:o}",
            "sha256": sha256(outputs[path].data),
        }
        for path in sorted(outputs)
    ]
    document = {
        "schema_version": 1,
        "generator": "codex/script-build-codex-skills.py",
        "phase": "phase-1-shared-adapter-generator",
        "skills": skills,
        "counts": {
            "skills": len(skills),
            "generated_files": len(files),
            "adapters": sum(1 for f in files if f["kind"] == "adapter"),
            "metadata": sum(1 for f in files if f["kind"] == "metadata"),
            "canonical_copies": sum(1 for f in files if f["kind"] == "canonical-copy"),
            "codex_native": sum(1 for f in files if f["kind"] == "codex-native"),
        },
        "protected": sorted(PROTECTED_PATHS)
        + sorted(
            f"{CODEX_SKILL_ROOT}/{name}/refs/compatibility-map.md"
            for name in skills + [SHARED]
        ),
        "files": files,
    }
    return (json.dumps(document, indent=2, sort_keys=False, ensure_ascii=False) + "\n").encode()


def previous_manifest_paths() -> set[str]:
    path = REPO / MANIFEST
    if not path.exists():
        return set()
    try:
        document = json.loads(path.read_text())
    except json.JSONDecodeError:
        return set()
    return {entry["path"] for entry in document.get("files", [])}


def apply(outputs: dict[str, Output], manifest: bytes, check_only: bool) -> tuple[int, int, list[str]]:
    written = 0
    removed = 0
    drift: list[str] = []

    for path in sorted(outputs):
        output = outputs[path]
        target = REPO / path
        current = target.read_bytes() if target.is_file() else None
        current_mode = (
            0o755 if target.is_file() and os.access(target, os.X_OK) else 0o644
        )
        if current == output.data and (not target.is_file() or current_mode == output.mode):
            continue
        drift.append(path)
        written += 1
        if check_only:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(output.data)
        target.chmod(output.mode)

    stale = sorted(previous_manifest_paths() - set(outputs))
    for path in stale:
        if is_protected(path):
            continue
        target = REPO / path
        if not target.exists():
            continue
        drift.append(f"stale:{path}")
        removed += 1
        if not check_only:
            target.unlink()

    manifest_path = REPO / MANIFEST
    if not manifest_path.is_file() or manifest_path.read_bytes() != manifest:
        drift.append(MANIFEST)
        if not check_only:
            manifest_path.write_bytes(manifest)

    if not check_only:
        prune_empty_dirs(REPO / ".agents")
    return written, removed, drift


def prune_empty_dirs(root: Path) -> None:
    if not root.exists():
        return
    for directory in sorted((p for p in root.rglob("*") if p.is_dir()), reverse=True):
        if not any(directory.iterdir()):
            directory.rmdir()


def unmanaged(outputs: dict[str, Output]) -> list[str]:
    root = REPO / ".agents"
    if not root.exists():
        return []
    known = set(outputs)
    found = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(REPO).as_posix()
        if rel in known or is_protected(rel):
            continue
        found.append(rel)
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify only; write nothing")
    args = parser.parse_args()

    skills = discover_skills(git_files(f"{CANONICAL_SKILL_ROOT}/**"))
    outputs = collect_outputs(skills)
    manifest = build_manifest(outputs, skills)
    written, removed, drift = apply(outputs, manifest, args.check)
    orphans = unmanaged(outputs)

    for path in orphans:
        print(f"UNMANAGED {path}")

    if args.check:
        for path in drift:
            print(f"DRIFT {path}")
        if drift:
            print(f"BUILD_CHECK fail drift={len(drift)}")
            return 1
        print(f"BUILD_CHECK pass skills={len(skills)} files={len(outputs)}")
        return 0

    print(
        f"BUILD_OK skills={len(skills)} generated={len(outputs)} "
        f"written={written} pruned={removed} unmanaged={len(orphans)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
