#!/usr/bin/env bash
# script-codex-ship.sh — the external-action broker for msg's two release gates.
#
# Generated by codex/script-build-codex-skills.py from codex/ship-template.sh.
# Do not hand-edit the generated copy under .agents/scripts/.
#
# Contract (DEV-CX-003 tool bindings and DEV-CX-008 external skills, both
# approved-translation; AMB-CX-001 and AMB-CX-006, both decided): pre-merge and
# merge are the only msg skills that reach outside the repository — they open a
# PR, merge one, deploy, submit to a store, cut a tag. On Claude those effects are
# spelled as commands inside a protocol. Spelled the same way on Codex they would
# be unverifiable: nothing would prove that pre-merge did not merge, that a clean
# run opened exactly one PR, or that a store submission was not announced as live.
#
# This helper is where every one of those actions is declared before it happens.
# It performs no external action itself — it records the intent, checks it against
# the canonical authority of the calling skill, and refuses the shapes that would
# quietly widen what a release gate is allowed to do:
#
#   * an actor taking an action its canonical contract does not own — above all
#     pre-merge merging, pushing or deploying anything (PMG-CX-003, MRG-CX-001)
#   * a second PR from one pre-merge run, or any PR at all on a failing verdict
#     (PMG-CX-004, PMG-CX-005)
#   * OPEN-PR reaching for `gh pr create` while kermit is available, or falling
#     back to it without naming the degradation — the loud-degrade rule of
#     AMB-CX-001; a silent fallback is the failure mode it exists to prevent
#   * a write outside the skill's sanctioned list, in the mode that sanctions it
#     (CX-G007, PMG-CX-008, MRG-CX-007)
#   * a production closing message that calls a store submission "live", or a
#     successful release that never says "success" (AMB-CX-006, MRG-CX-008)
#
# Usage:
#   script-codex-ship.sh action --actor pre-merge|merge --action <name> \
#                               [--target <ref>] [--verdict clean|failing] \
#                               [--tool kermit|gh] [--degraded <reason>] \
#                               [--ledger <file>]
#   script-codex-ship.sh writes --actor pre-merge|merge --mode <mode> \
#                               --path <p> [--path <p> ...]
#   script-codex-ship.sh close  --model deploy|submission --result success|failed \
#                               --text <closing message>
#
# Actions by actor (the canonical authority, not a convenience list):
#   pre-merge   sync-merge · pr-open · report-write · issues-write
#   merge       pr-open · pr-merge · deploy · submit · tag · stamp · rollback
#
# Write modes:
#   pre-merge   gate · init · update-criticality
#   merge       staging · production · init
#
# Environment:
#   MSG_CODEX_KERMIT     present (default) | absent — is `$kermit` on this host
#   MSG_CODEX_SHIP_MODE  stubbed (default) | live — evals never leave `stubbed`;
#                        anything else is refused rather than executed
#
# Exit codes (designed outcomes, not harness incidents):
#   0  the action/write/closing is within contract; the proof lines are on stdout
#   2  usage error
#   4  SHIP_STATE=forbidden        — the actor does not own this action
#   5  SHIP_STATE=refused          — a clean-run-only action on a failing verdict
#   6  SHIP_STATE=duplicate-pr     — a second PR from one gate run
#   7  SHIP_STATE=silent-degrade   — the kermit fallback was taken or hidden wrongly
#   8  WRITE_STATE=forbidden       — a write outside the sanctioned list
#   9  CLOSE_STATE=forbidden       — banned or missing terminal wording
#  10  SHIP_STATE=live-refused     — the broker was asked to act for real

set -euo pipefail

LEDGER_DEFAULT=".msg-codex-ship.tsv"

usage_error() { echo "script-codex-ship.sh: $1" >&2; exit 2; }

# --- action ----------------------------------------------------------------- #

action() {
  local actor="" name="" target="" verdict="clean" tool="" degraded="" ledger="$LEDGER_DEFAULT"
  while [ $# -gt 0 ]; do
    case "$1" in
      --actor)    actor="${2:-}"; shift 2 ;;
      --action)   name="${2:-}"; shift 2 ;;
      --target)   target="${2:-}"; shift 2 ;;
      --verdict)  verdict="${2:-}"; shift 2 ;;
      --tool)     tool="${2:-}"; shift 2 ;;
      --degraded) degraded="${2:-}"; shift 2 ;;
      --ledger)   ledger="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$actor" ] || usage_error "--actor is required"
  [ -n "$name" ] || usage_error "--action is required"
  case "$actor" in
    pre-merge|merge) ;;
    *) usage_error "--actor must be pre-merge or merge" ;;
  esac
  case "$verdict" in
    clean|failing) ;;
    *) usage_error "--verdict must be clean or failing" ;;
  esac

  local mode="${MSG_CODEX_SHIP_MODE:-stubbed}"
  case "$mode" in
    stubbed) ;;
    live)
      printf 'SHIP_ACTOR=%s\n' "$actor"
      printf 'SHIP_ACTION=%s\n' "$name"
      echo "SHIP_STATE=live-refused"
      echo "REASON=this broker only records intent; a real external effect is never performed from a compatibility run"
      exit 10 ;;
    *) usage_error "unknown MSG_CODEX_SHIP_MODE: $mode" ;;
  esac

  local allowed=""
  case "$actor" in
    pre-merge) allowed="sync-merge pr-open report-write issues-write" ;;
    merge)     allowed="pr-open pr-merge deploy submit tag stamp rollback" ;;
  esac

  local candidate owned=0
  for candidate in $allowed; do
    [ "$candidate" = "$name" ] && owned=1
  done
  if [ "$owned" -ne 1 ]; then
    printf 'SHIP_ACTOR=%s\n' "$actor"
    printf 'SHIP_ACTION=%s\n' "$name"
    echo "SHIP_STATE=forbidden"
    case "$actor:$name" in
      pre-merge:pr-merge|pre-merge:deploy|pre-merge:submit|pre-merge:tag)
        printf 'REASON=pre-merge opens its one PR and stops; %s belongs to merge, the only skill that ships\n' "$name" ;;
      *)
        printf 'REASON=%s does not own the action %s; its authority is: %s\n' "$actor" "$name" "$allowed" ;;
    esac
    exit 4
  fi

  # A PR is the clean-verdict terminal. A failing gate writes issues instead.
  if [ "$name" = "pr-open" ] && [ "$actor" = "pre-merge" ] && [ "$verdict" = "failing" ]; then
    echo "SHIP_ACTION=pr-open"
    echo "SHIP_STATE=refused"
    echo "REASON=a failing verdict opens no PR; the run writes the paired issues file and offers the fix loop"
    exit 5
  fi

  # Exactly one PR per gate run, counted from the ledger rather than remembered.
  if [ "$name" = "pr-open" ] && [ -f "$ledger" ] \
     && awk -F'\t' -v a="$actor" '$1 == a && $2 == "pr-open" { found = 1 } END { exit !found }' "$ledger"; then
    echo "SHIP_ACTION=pr-open"
    echo "SHIP_STATE=duplicate-pr"
    printf 'REASON=%s already opened a PR in this run; a clean verdict opens exactly one\n' "$actor"
    exit 6
  fi

  # OPEN-PR goes through kermit. `gh pr create` is a fallback that must be both
  # necessary and named — never a quiet substitution.
  if [ "$name" = "pr-open" ]; then
    local kermit="${MSG_CODEX_KERMIT:-present}"
    case "$kermit" in
      present|absent) ;;
      *) usage_error "unknown MSG_CODEX_KERMIT: $kermit" ;;
    esac
    [ -n "$tool" ] || tool="kermit"
    case "$tool" in
      kermit|gh) ;;
      *) usage_error "--tool must be kermit or gh" ;;
    esac
    if [ "$tool" = "kermit" ] && [ "$kermit" = "absent" ]; then
      echo "SHIP_ACTION=pr-open"
      echo "SHIP_STATE=silent-degrade"
      echo "REASON=kermit is not available on this host; the fallback is gh pr create and it must be declared"
      exit 7
    fi
    if [ "$tool" = "gh" ] && [ "$kermit" = "present" ]; then
      echo "SHIP_ACTION=pr-open"
      echo "SHIP_STATE=silent-degrade"
      echo "REASON=kermit is available; OPEN-PR does not bypass it"
      exit 7
    fi
    if [ "$tool" = "gh" ] && [ -z "$degraded" ]; then
      echo "SHIP_ACTION=pr-open"
      echo "SHIP_STATE=silent-degrade"
      echo "REASON=the gh fallback was taken without naming the degradation; a silent skip of kermit is never allowed"
      exit 7
    fi
    printf 'PR_TOOL=%s\n' "$tool"
    [ -n "$degraded" ] && printf 'PR_DEGRADED=%s\n' "$degraded"
  fi

  printf '%s\t%s\t%s\n' "$actor" "$name" "$target" >> "$ledger"
  printf 'SHIP_ACTOR=%s\n' "$actor"
  printf 'SHIP_ACTION=%s\n' "$name"
  [ -n "$target" ] && printf 'SHIP_TARGET=%s\n' "$target"
  echo "EXTERNAL_EFFECT=stubbed"
  echo "SHIP_STATE=recorded"
  exit 0
}

# --- writes ----------------------------------------------------------------- #

# The sanctioned list is per skill AND per mode: a normal pre-merge gate is
# read-only over everything except its own artifacts, while `--init` may write
# the config it just got approval for. Collapsing the modes into one list would
# silently give the gate run init's authority.
sanctioned_patterns() {
  case "$1:$2" in
    pre-merge:gate)
      printf '%s\n' '.pre-merge/*' 'reports/*' 'devkit/DOCTOR.md' ;;
    pre-merge:init)
      printf '%s\n' '.pre-merge/*' 'reports/*' 'devkit/DOCTOR.md' 'devkit/policy.json' \
        'devkit/ENV.md' '.github/workflows/*' 'eslint.config.js' 'biome.json' 'ruff.toml' \
        'vitest.config.ts' 'playwright.config.ts' '.prettierrc.json' '.size-limit.json' \
        'docker-compose.test.yml' ;;
    pre-merge:update-criticality)
      printf '%s\n' '.pre-merge/*' 'reports/*' 'devkit/DOCTOR.md' 'devkit/policy.json' \
        '*test*' '*spec*' ;;
    merge:staging)
      printf '%s\n' '.merge/*' 'reports/*' 'devkit/DOCTOR.md' 'features/*' ;;
    merge:production)
      printf '%s\n' '.merge/*' 'reports/*' 'devkit/DOCTOR.md' 'features/*' 'INTAKE.md' ;;
    merge:init)
      printf '%s\n' '.merge/*' 'reports/*' 'devkit/DOCTOR.md' 'devkit/policy.json' \
        '.github/workflows/*' ;;
    *) return 1 ;;
  esac
}

writes() {
  local actor="" mode="" paths=()
  while [ $# -gt 0 ]; do
    case "$1" in
      --actor) actor="${2:-}"; shift 2 ;;
      --mode)  mode="${2:-}"; shift 2 ;;
      --path)  paths+=("${2:-}"); shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  [ -n "$actor" ] || usage_error "--actor is required"
  [ -n "$mode" ] || usage_error "--mode is required"
  [ "${#paths[@]}" -ge 1 ] || usage_error "at least one --path is required"

  local patterns
  patterns="$(sanctioned_patterns "$actor" "$mode")" \
    || usage_error "no sanctioned write list for $actor in mode $mode"

  local path pattern matched
  for path in "${paths[@]}"; do
    # PLATFORMS.md is the one file merge --init explicitly does not write, so it
    # gets its own refusal rather than falling through the generic one.
    if [ "$actor" = "merge" ] && [ "$path" = "devkit/PLATFORMS.md" ]; then
      printf 'WRITE_PATH=%s\n' "$path"
      echo "WRITE_STATE=forbidden"
      echo "REASON=merge --init never writes devkit/PLATFORMS.md; the platform inventory belongs to msg --init"
      exit 8
    fi
    matched=0
    while IFS= read -r pattern; do
      # shellcheck disable=SC2254
      case "$path" in $pattern) matched=1 ;; esac
    done <<< "$patterns"
    if [ "$matched" -ne 1 ]; then
      printf 'WRITE_PATH=%s\n' "$path"
      echo "WRITE_STATE=forbidden"
      printf 'REASON=%s in mode %s may not write %s; product source is repaired through eng, never by a release gate\n' \
        "$actor" "$mode" "$path"
      exit 8
    fi
    printf 'WRITE_OK=%s\n' "$path"
  done
  printf 'WRITE_STATE=sanctioned actor=%s mode=%s paths=%s\n' "$actor" "$mode" "${#paths[@]}"
  exit 0
}

# --- close ------------------------------------------------------------------ #

close() {
  local model="" result="" text=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --model)  model="${2:-}"; shift 2 ;;
      --result) result="${2:-}"; shift 2 ;;
      --text)   text="${2:-}"; shift 2 ;;
      *) usage_error "unknown argument: $1" ;;
    esac
  done
  case "$model" in
    deploy|submission) ;;
    *) usage_error "--model must be deploy or submission" ;;
  esac
  case "$result" in
    success|failed) ;;
    *) usage_error "--result must be success or failed" ;;
  esac
  [ -n "$text" ] || usage_error "--text is required"

  local lowered probe
  lowered="$(printf '%s' "$text" | tr '[:upper:]' '[:lower:]')"

  # A store submission is accepted for review, not serving users. "live" is the
  # single word that turns an accurate terminal into a false one — as a claim
  # about the release. The canonical contract's own compounds (`live-to-users
  # is not yet true`, the `live_status` polling seam) are the opposite claim and
  # are removed before the check rather than caught by it.
  probe="$(printf '%s' "$lowered" | sed -e 's/live-to-users//g' -e 's/live_status//g')"
  if [ "$model" = "submission" ] && printf '%s' "$probe" | grep -qE '(^|[^a-z])live([^a-z]|$)'; then
    printf 'CLOSE_MODEL=%s\n' "$model"
    echo "CLOSE_STATE=forbidden"
    echo "REASON=a submission release is submitted, never live; liveness would require store-status polling merge does not do"
    exit 9
  fi
  if [ "$result" = "success" ] && ! printf '%s' "$lowered" | grep -q 'success'; then
    printf 'CLOSE_MODEL=%s\n' "$model"
    echo "CLOSE_STATE=forbidden"
    echo "REASON=a green production release closes as success; the terminal must state the outcome it reached"
    exit 9
  fi
  printf 'CLOSE_MODEL=%s\n' "$model"
  printf 'CLOSE_RESULT=%s\n' "$result"
  echo "CLOSE_STATE=accepted"
  exit 0
}

main() {
  local mode="${1:-}"
  [ $# -gt 0 ] && shift || true
  case "$mode" in
    action) action "$@" ;;
    writes) writes "$@" ;;
    close) close "$@" ;;
    -h|--help) sed -n '2,62p' "$0" ;;
    *) usage_error "usage: $0 action|writes|close [...]" ;;
  esac
}

main "$@"
